#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.1.4

PKG_DEPENDS="alsa-lib ncurses"
PKG_MAINTAINER="Jaroslav Kysela <perex@perex.cz>"
PKG_SECTION="audio"
PKG_SHORTDESC="Advanced Linux Sound Architecture utilities"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
