#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.26.3

PKG_DEPENDS="glib libXtst"
PKG_MAINTAINER="Mike Gorse <mgorse@novell.com>, et al"
PKG_SECTION="gnome"
PKG_SHORTDESC="AT SPI CORE"

buildpkg() {
   ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
