#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.0.1

PKG_DEPENDS="libX11"
PKG_MAINTAINER="Sasha Vasko <sasha@aftercode.net>"
PKG_SECTION="apps"
PKG_SHORTDESC="Terminal Emulator for AfterStep"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  cp ../doc . -r
  sed -i "s/-s //g" `find . -name Makefile`
  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
