#!/bin/bash

PKG_NAME=$1
PKG_VERSION=3.2.0

PKG_DEPENDS="ORBit2"
PKG_MAINTAINER="Havoc Pennington <hp@redhat.com>"
PKG_SECTION="gnome"
PKG_SHORTDESC="GConf is a system for storing application preferences."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS}

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
