#!/bin/bash

PKG_NAME=$1
PKG_VERSION=3.22.2

PKG_DEPENDS="dconf vte GConf gsettings-desktop-schemas"
PKG_MAINTAINER="Guilherme de S. Pastore <gpastore@gnome.org>, et al"
PKG_SECTION="gnome"
PKG_SHORTDESC="A terminal emulator for GNOME."

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --without-nautilus-extension \
      --disable-search-provider

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
