#!/bin/bash

PKG_NAME=$1
PKG_VERSION=2.0.14

PKG_DEPENDS="libjpeg-turbo"
PKG_MAINTAINER="Michael Adams"
PKG_SECTION="graphics"
PKG_SHORTDESC="JPEG-2000 Part-1 standard (i.e., ISO/IEC 15444-1) implementation"

buildpkg() {
  cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
    -DCMAKE_C_COMPILER=aarch64-linux-gcc \
    -DCMAKE_CXX_COMPILER=aarch64-linux-g++ \
    -DCMAKE_CPP_COMPILER=aarch64-linux-cpp \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_EXE_LINKER_FLAGS="-lm" \
    -DENABLE_STATIC=OFF

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
