#!/bin/bash

PKG_NAME=$1
PKG_VERSION=1.3.0

PKG_DEPENDS="libXext"
PKG_MAINTAINER="Dave Gamble"
PKG_SECTION="graphics"
PKG_SHORTDESC="GL Vendor-Neutral Dispatch library"

buildpkg() {
  ../configure ${TARGET_CONFIGURE_OPTS} \
      --enable-static

  make $MAKEFLAGS
  make DESTDIR=$INSTALL_PKG install
}
